// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZhH3zarhmr8NeXFDVOx4GwctvCuMddAI',
    appId: '1:452433586152:web:a8c13ebadeb2078c69665d',
    messagingSenderId: '452433586152',
    projectId: 'ulearningapp-bloc',
    authDomain: 'ulearningapp-bloc.firebaseapp.com',
    storageBucket: 'ulearningapp-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGibywc5G_11daLidzbHGf61XyAHpMjw',
    appId: '1:452433586152:android:eae8e3ecf16dda8869665d',
    messagingSenderId: '452433586152',
    projectId: 'ulearningapp-bloc',
    storageBucket: 'ulearningapp-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Qa83OHhYV_2-D9LpATEQDu40WXrU974',
    appId: '1:452433586152:ios:751804305eb77f4669665d',
    messagingSenderId: '452433586152',
    projectId: 'ulearningapp-bloc',
    storageBucket: 'ulearningapp-bloc.appspot.com',
    iosClientId: '452433586152-3uor82oab143eb60fgv236g0b47fl134.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseSelling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0Qa83OHhYV_2-D9LpATEQDu40WXrU974',
    appId: '1:452433586152:ios:65a20e8192d95a8869665d',
    messagingSenderId: '452433586152',
    projectId: 'ulearningapp-bloc',
    storageBucket: 'ulearningapp-bloc.appspot.com',
    iosClientId: '452433586152-gbh6ueq582fkvin8a3f6inufc3ksvfm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseSelling.RunnerTests',
  );
}
